// Date: 2014/10/6 星期一 0:29:26
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package cn.otfurniture.client.model;

import cn.liutils.api.client.model.ITileEntityModel;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.tileentity.TileEntity;

public class ModelDeadRabbit extends ModelBase implements ITileEntityModel {
	// fields
	ModelRenderer head;
	ModelRenderer body;
	ModelRenderer ear1;
	ModelRenderer ear2;
	ModelRenderer leg1;
	ModelRenderer leg2;
	ModelRenderer leg3;
	ModelRenderer leg4;
	ModelRenderer tail;

	public ModelDeadRabbit() {
		textureWidth = 64;
		textureHeight = 32;

		head = new ModelRenderer(this, 18, 0);
		head.addBox(0F, 0F, 0F, 3, 3, 3);
		head.setRotationPoint(-1.5F, 22.5F, -4F);
		head.setTextureSize(64, 32);
		head.mirror = true;
		setRotation(head, 1F, 0F, 0F);
		body = new ModelRenderer(this, 0, 0);
		body.addBox(0F, 0F, 0F, 4, 2, 5);
		body.setRotationPoint(-2F, 22F, -1F);
		body.setTextureSize(64, 32);
		body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
		ear1 = new ModelRenderer(this, 30, 0);
		ear1.addBox(0F, 0F, 0F, 1, 2, 3);
		ear1.setRotationPoint(1F, 22F, -6F);
		ear1.setTextureSize(64, 32);
		ear1.mirror = true;
		setRotation(ear1, 0.5F, 0F, 0F);
		ear2 = new ModelRenderer(this, 30, 0);
		ear2.addBox(0F, 0F, 0F, 1, 2, 3);
		ear2.setRotationPoint(-2F, 22F, -6F);
		ear2.setTextureSize(64, 32);
		ear2.mirror = true;
		setRotation(ear2, 0.5F, 0F, 0F);
		leg1 = new ModelRenderer(this, 6, 7);
		leg1.addBox(0F, 0F, 0F, 2, 3, 2);
		leg1.setRotationPoint(0.5F, 20F, 3F);
		leg1.setTextureSize(64, 32);
		leg1.mirror = true;
		setRotation(leg1, 0F, 0F, 0F);
		leg2 = new ModelRenderer(this, 0, 7);
		leg2.addBox(0F, 0F, 0F, 1, 2, 2);
		leg2.setRotationPoint(-2.5F, 21F, -1F);
		leg2.setTextureSize(64, 32);
		leg2.mirror = true;
		setRotation(leg2, 0F, 0F, 0F);
		leg3 = new ModelRenderer(this, 0, 7);
		leg3.addBox(0F, 0F, 0F, 1, 2, 2);
		leg3.setRotationPoint(1.5F, 21F, -1F);
		leg3.setTextureSize(64, 32);
		leg3.mirror = true;
		setRotation(leg3, 0F, 0F, 0F);
		leg4 = new ModelRenderer(this, 6, 7);
		leg4.addBox(0F, 0F, 0F, 2, 3, 2);
		leg4.setRotationPoint(-2.5F, 20F, 3F);
		leg4.setTextureSize(64, 32);
		leg4.mirror = true;
		setRotation(leg4, 0F, 0F, 0F);
		tail = new ModelRenderer(this, 14, 7);
		tail.addBox(0F, 0F, 0F, 2, 2, 2);
		tail.setRotationPoint(-1F, 23F, 4F);
		tail.setTextureSize(64, 32);
		tail.mirror = true;
		setRotation(tail, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		head.render(f5);
		body.render(f5);
		ear1.render(f5);
		ear2.render(f5);
		leg1.render(f5);
		leg2.render(f5);
		leg3.render(f5);
		leg4.render(f5);
		tail.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void render(TileEntity is, float f1, float f) {
		float f5 = 1;
		head.render(f5);
		body.render(f5);
		ear1.render(f5);
		ear2.render(f5);
		leg1.render(f5);
		leg2.render(f5);
		leg3.render(f5);
		leg4.render(f5);
		tail.render(f5);
	}

	@Override
	public void renderPart(TileEntity te, String name, float f1, float f) {
		throw new UnsupportedOperationException();
	}

}
